features = """
Full Support for Bot API 9.3

.. warning::

    Bot API 9.3 deprecates the argument ``exclude_limited`` of ``Bot.get_business_account_gifts`` in favor of the new arguments ``exclude_limited_upgradable`` and ``exclude_limited_non_upgradable``. The argument ``exclude_limited`` is still present in PTB for backward compatibility, but it will be removed in future releases. Please update your code accordingly.
"""

pull_requests = [
  { uid = "5086", author_uids = ["Bibo-Joshi"] },
  { uid = "5078", author_uid = "aelkheir", closes_threads = ["5077"] },
  { uid = "5079", author_uid = "aelkheir" },
  { uid = "5084", author_uids = ["Bibo-Joshi"] },
  { uid = "5085", author_uids = ["Bibo-Joshi"] },
  { uid = "5095", author_uids = ["Bibo-Joshi"] },
]
