highlights = "Hand over Maintainer Role from `Bibo-Joshi <https://github.com/Bibo-Joshi>`_ to `Poolitzer <https://github.com/Poolitzer>`_ and `Harshil <https://github.com/harshil21>`_"

[[pull_requests]]
uid = "5119"
author_uids = ["Bibo-Joshi"]
