# Make sure that the additional_dependencies here match requirements(-opts).txt

ci:
    autofix_prs: false
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.4.3'
    hooks:
    -   id: ruff
        name: ruff
        additional_dependencies:
          - httpx~=0.27
          - tornado~=6.4
          - APScheduler~=3.10.4
          - cachetools~=5.3.3
          - aiolimiter~=1.1.0
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
    -   id: black
        args:
        - --diff
        - --check
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: v3.1.0
    hooks:
    -   id: pylint
        files: ^(?!(tests|docs)).*\.py$
        additional_dependencies:
          - httpx~=0.27
          - tornado~=6.4
          - APScheduler~=3.10.4
          - cachetools~=5.3.3
          - aiolimiter~=1.1.0
          - . # this basically does `pip install -e .`
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        name: mypy-ptb
        files: ^(?!(tests|examples|docs)).*\.py$
        additional_dependencies:
          - types-pytz
          - types-cryptography
          - types-cachetools
          - httpx~=0.27
          - tornado~=6.4
          - APScheduler~=3.10.4
          - cachetools~=5.3.3
          - aiolimiter~=1.1.0
          - . # this basically does `pip install -e .`
    - id: mypy
      name: mypy-examples
      files: ^examples/.*\.py$
      args:
        - --no-strict-optional
        - --follow-imports=silent
      additional_dependencies:
        - tornado~=6.4
        - APScheduler~=3.10.4
        - cachetools~=5.3.3
        - . # this basically does `pip install -e .`
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args:
          - --py38-plus
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort
        args:
        - --diff
        - --check
