# Make sure that
#   * the revs specified here match requirements-dev.txt
#   * the makefile checks the same files as pre-commit
repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args:
        - --diff
        - --check
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        files: ^(telegram|examples)/.*\.py$
        args:
        - --rcfile=setup.cfg
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        files: ^(telegram|examples)/.*\.py$
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
    -   id: pyupgrade
        files: ^(telegram|examples|tests)/.*\.py$
        args:
            - --py36-plus
