repos:
-   repo: git://github.com/python-telegram-bot/mirrors-yapf
    rev: 5769e088ef6e0a0d1eb63bd6d0c1fe9f3606d6c8
    hooks:
    -   id: yapf
        files: ^(telegram|tests)/.*\.py$
        args:
        - --diff
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    -   id: flake8
-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.5.3
    hooks:
    -   id: pylint
        files: ^telegram/.*\.py$
        args:
        - --errors-only
        - --disable=import-error
