# Make sure that
#   * the revs specified here match requirements-dev.txt
#   * the additional_dependencies here match requirements.txt

ci:
    autofix_prs: false
    autoupdate_schedule: monthly
    # We currently only need this behavior on the v13.x branch were we have the vendored urllib
    # TODO: Remove once we discontinue v13
    submodules: true

repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
        - --diff
        - --check
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: v2.13.9
    hooks:
    -   id: pylint
        files: ^(telegram|examples)/.*\.py$
        args:
          - --rcfile=setup.cfg
          #  run pylint across multiple cpu cores to speed it up-
          # https://pylint.pycqa.org/en/latest/user_guide/run.html?#parallel-execution to know more
          - --jobs=0

        additional_dependencies:
          - httpx~=0.22.0
          - tornado~=6.1
          - APScheduler~=3.9.1
          - cachetools~=5.0.0
          - . # this basically does `pip install -e .`
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
    -   id: mypy
        name: mypy-ptb
        files: ^telegram/.*\.py$
        additional_dependencies:
          - types-ujson
          - types-pytz
          - types-cryptography
          - types-cachetools
          - httpx~=0.22.0
          - tornado~=6.1
          - APScheduler~=3.9.1
          - cachetools~=5.0.0
          - . # this basically does `pip install -e .`
    - id: mypy
      name: mypy-examples
      files: ^examples/.*\.py$
      args:
        - --no-strict-optional
        - --follow-imports=silent
      additional_dependencies:
        - tornado~=6.1
        - APScheduler~=3.9.1
        - cachetools~=5.0.0
        - . # this basically does `pip install -e .`
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    -   id: pyupgrade
        files: ^(telegram|examples|tests)/.*\.py$
        args:
          - --py37-plus
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
        args:
        - --diff
        - --check
