-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: 316b795b2f32cbe80047aff7e842b72368d5a2c1
    hooks:
    -   id: yapf
        files: ^(telegram|tests)/.*\.py$
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 6dfcb89af3c9b4d172cc2e5a8a2fa0f54615a338
    hooks:
    -   id: flake8
        files: ^telegram/.*\.py$
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: 4de6c8dfadef1a271a814561ce05b8bc1c446d22
    hooks:
    -   id: pylint
        files: ^telegram/.*\.py$
        args:
        - --errors-only
        - --disable=no-name-in-module,import-error
