ci:
    autofix_prs: false
    # We use Renovate to update this file now, but we can't disable automatic pre-commit updates
    # when using the `pre-commit` GitHub Action, so we set the schedule to quarterly to avoid
    # frequent updates.
    autoupdate_schedule: quarterly
    autoupdate_commit_msg: 'Bump `pre-commit` Hooks to Latest Versions'

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.13.1'
    hooks:
    # Run the linter:
    -   id: ruff-check
        name: ruff check
    # Run the formatter:
    -   id: ruff-format
        name: ruff format
-   repo: https://github.com/PyCQA/pylint
    rev: v3.3.8
    hooks:
    -   id: pylint
        files: ^(?!(tests|docs)).*\.py$
        language: python
        additional_dependencies:
          - httpx~=0.27
          - tornado~=6.4
          - APScheduler>=3.10.4,<3.12.0
          - cachetools>=5.3.3,<6.3.0
          - aiolimiter~=1.1,<1.3
          - . # this basically does `pip install -e .`
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    -   id: mypy
        name: mypy-ptb
        files: ^(?!(tests|examples|docs)).*\.py$
        language: python
        additional_dependencies:
          - types-pytz
          - types-cryptography
          - types-cachetools
          - httpx~=0.27
          - tornado~=6.4
          - APScheduler>=3.10.4,<3.12.0
          - cachetools>=5.3.3,<6.3.0
          - aiolimiter~=1.1,<1.3
          - . # this basically does `pip install -e .`
    - id: mypy
      name: mypy-examples
      files: ^examples/.*\.py$
      language: python
      args:
        - --no-strict-optional
        - --follow-imports=silent
      additional_dependencies:
        - tornado~=6.4
        - APScheduler>=3.10.4,<3.12.0
        - cachetools>=5.3.3,<6.3.0
        - . # this basically does `pip install -e .`
