language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy-5.7.1"

dist: trusty
sudo: false

branches:
  only:
    - master
    - /^[vV]\d+$/

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pre-commit
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -f $HOME/.pre-commit/pre-commit.log

install:
  - pip install -U codecov pytest-cov
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7'* ]]; then pip install -U git+https://github.com/yaml/pyyaml.git; fi
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install ujson; fi

script:
  - pytest -v -m nocoverage
  - pytest -v -m "not nocoverage" --cov

after_success:
  - coverage combine
  - codecov -F Travis
