language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.7.1"
  - "pypy3.5-5.8.0"

dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pre-commit
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -f $HOME/.pre-commit/pre-commit.log

install:
  - pip install -U codecov pytest-cov
  - pip install -U wheel
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install ujson; fi

script:
  - pytest -v -m nocoverage
  - pytest -v -m "not nocoverage" --cov

after_success:
  - coverage combine
  - codecov