name: Chango
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  create-chango-fragment:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    name: Create chango Fragment
    runs-on: ubuntu-latest
    outputs:
      IS_RELEASE_PR: ${{ steps.check_title.outputs.IS_RELEASE_PR }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # needed for commit and push step at the end
          persist-credentials: true
      - name: Check PR Title
        id: check_title
        run: | # zizmor: ignore[template-injection]
          if [[ "$(echo "${{ github.event.pull_request.title }}" | tr '[:upper:]' '[:lower:]')" =~ ^bump\ version\ to\ .* ]]; then
            echo "COMMIT_AND_PUSH=false" >> $GITHUB_OUTPUT
            echo "IS_RELEASE_PR=true" >> $GITHUB_OUTPUT
          else
            echo "COMMIT_AND_PUSH=true" >> $GITHUB_OUTPUT
            echo "IS_RELEASE_PR=false" >> $GITHUB_OUTPUT
          fi

      # Create the new fragment
      - uses: Bibo-Joshi/chango@9d6bd9d7612eca5fab2c5161687011be59baaf19 # v0.4.0
        with:
          github-token: ${{ secrets.CHANGO_PAT }}
          query-issue-types: true
          commit-and-push: ${{ steps.check_title.outputs.COMMIT_AND_PUSH }}

      # Run `chango release` if applicable - needs some additional setup.
      - name: Set up Python
        if: steps.check_title.outputs.IS_RELEASE_PR == 'true'
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.x"

      - name: Do Release
        if: steps.check_title.outputs.IS_RELEASE_PR == 'true'
        run: |
          cd ./target-repo
          git add changes/unreleased/*
          pip install . --group docs
          VERSION_TAG=$(python -c "from telegram import __version__; print(f'{__version__}')")
          chango release --uid $VERSION_TAG

      - name: Commit & Push
        if: steps.check_title.outputs.IS_RELEASE_PR == 'true'
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: "Do chango Release"
          repository: ./target-repo
