name: PR Labeler

on:
  pull_request:
    types: [opened]

jobs:
  pre-commit-ci:
    permissions:
      contents: read # for srvaroa/labeler to read config file
      pull-requests: write # for srvaroa/labeler to add labels in PR
    runs-on: ubuntu-latest
    steps:
    - uses: srvaroa/labeler@v1.10.0
      # Config file at .github/labeler.yml
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
