name: 'Mark & close stale questions'
on:
  workflow_dispatch:
# Currently disabled due to https://github.com/actions/stale/pull/1298
#  schedule:
#    - cron: '42 2 * * *'

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      # For adding labels and closing
      issues: write
    steps:
      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          # PRs never get stale
          days-before-stale: 3
          days-before-close: 2
          days-before-pr-stale: -1
          stale-issue-label: 'üìã stale'
          only-issue-types: '‚ùî question'
          stale-issue-message: ''
          close-issue-message: 'This issue has been automatically closed due to inactivity. Feel free to comment in order to reopen or ask again in our Telegram support group at https://t.me/pythontelegrambotgroup.'
